version: '3.1'

services:

  httpd:
    image: httpd
    ports:
      - 8080:80
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
    networks:
      app_net:
        ipv4_address: 172.16.238.8

  mysql:
    image: mariadb
    # command: mysql -u root -p example test < /_mysql_root/install.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  php:
    image: php:7
    command: bash -c "docker-php-ext-install mysqli && docker-php-ext-install mysqli && php -S 0.0.0.0:8000 /_root/index.php"
    ports: 
      - 8000:8000
    volumes:
      - ./public_html:/_root/
    links:
      - mysql:mysql
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  adminer:
    image: adminer
    ports:
      - 8088:8080
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  dockerui:
    image: kevan/dockerui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
      - 9000:9000

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24